"""
SprintSynergy — Universal Tool Configuration
Supports: Jira, Rally, Azure DevOps, Trello, Monday.com, Linear, Custom
"""

# ── TOOL DEFINITIONS ──────────────────────────────────────────────────────
# Each tool defines its own fields, labels, help text, and URL pattern

TOOLS = {
    "Jira": {
        "icon":         "🔵",
        "vendor":       "Atlassian",
        "url_label":    "Jira Instance URL",
        "url_help":     "Your Jira Cloud URL — e.g. https://yourorg.atlassian.net",
        "url_example":  "https://yourorg.atlassian.net",
        "auth_type":    "api_token",
        "email_label":  "Atlassian Email",
        "email_help":   "The email you use to log in to Jira",
        "token_label":  "API Token",
        "token_help":   "Generate at: id.atlassian.com → Security → API Tokens",
        "token_link":   "https://id.atlassian.com/manage-profile/security/api-tokens",
        "token_ph":     "ATATT3x...",
        "test_path":    "/rest/api/3/myself",
        "test_auth":    "basic",
        "board_label":  "Board ID",
        "board_help":   "Number from your board URL: /boards/34 → enter 34",
        "project_label":"Project Key",
        "project_help": "e.g. AES, PROJ, SCRUM",
        "color":        "#0052CC",
        "adapter":      "jira",
    },
    "Rally (CA Agile)": {
        "icon":         "🔴",
        "vendor":       "Broadcom",
        "url_label":    "Rally Instance URL",
        "url_help":     "Usually https://rally1.rallydev.com — or your private instance",
        "url_example":  "https://rally1.rallydev.com",
        "auth_type":    "api_key",
        "email_label":  "Rally Email (optional)",
        "email_help":   "Your Rally login email — used for reference only",
        "token_label":  "Rally API Key",
        "token_help":   "In Rally: Profile → API Keys → Create new key",
        "token_link":   "https://rally1.rallydev.com",
        "token_ph":     "_abc123XYZ...",
        "test_path":    "/slm/webservice/v2.0/subscription",
        "test_auth":    "rally_key",
        "board_label":  "Project OID / Workspace ID",
        "board_help":   "Found in Rally URL: /slm/rally.sp#/workspace/12345",
        "project_label":"Rally Project Name",
        "project_help": "Exact project name as shown in Rally",
        "color":        "#E8362D",
        "adapter":      "rally",
    },
    "Azure DevOps": {
        "icon":         "🔷",
        "vendor":       "Microsoft",
        "url_label":    "Azure DevOps Organization URL",
        "url_help":     "https://dev.azure.com/yourorganisation",
        "url_example":  "https://dev.azure.com/yourorg",
        "auth_type":    "pat",
        "email_label":  "Microsoft Email",
        "email_help":   "Your Microsoft / Azure AD login email",
        "token_label":  "Personal Access Token (PAT)",
        "token_help":   "Azure DevOps → User Settings → Personal Access Tokens → New Token",
        "token_link":   "https://dev.azure.com",
        "token_ph":     "PAT token...",
        "test_path":    "/_apis/projects?api-version=7.0",
        "test_auth":    "basic_empty_user",
        "board_label":  "Board ID",
        "board_help":   "Found in board URL: /boards?boardId=123",
        "project_label":"Project Name",
        "project_help": "Exact project name in Azure DevOps",
        "color":        "#0078D4",
        "adapter":      "azure",
    },
    "Trello": {
        "icon":         "🟦",
        "vendor":       "Atlassian",
        "url_label":    "Trello API URL",
        "url_help":     "Always: https://api.trello.com/1 — do not change",
        "url_example":  "https://api.trello.com/1",
        "auth_type":    "trello_key_token",
        "email_label":  "Trello API Key",
        "email_help":   "Get from: https://trello.com/power-ups/admin → API Key",
        "token_label":  "Trello Token",
        "token_help":   "After getting API key — click Token link on the same page",
        "token_link":   "https://trello.com/power-ups/admin",
        "token_ph":     "Trello token...",
        "test_path":    "/members/me",
        "test_auth":    "trello_params",
        "board_label":  "Board Short ID",
        "board_help":   "Found in board URL: trello.com/b/ABC123/board-name → ABC123",
        "project_label":"Board Name",
        "project_help": "Name of your Trello board",
        "color":        "#0052CC",
        "adapter":      "trello",
    },
    "Monday.com": {
        "icon":         "🟠",
        "vendor":       "Monday.com",
        "url_label":    "Monday API URL",
        "url_help":     "Always: https://api.monday.com/v2 — do not change",
        "url_example":  "https://api.monday.com/v2",
        "auth_type":    "bearer",
        "email_label":  "Monday Email (optional)",
        "email_help":   "Your Monday.com login email — for reference only",
        "token_label":  "Monday API Token",
        "token_help":   "Monday.com → Profile → Developers → API → Copy token",
        "token_link":   "https://monday.com/apps/manage/tokens",
        "token_ph":     "eyJhbGci...",
        "test_path":    "/v2",
        "test_auth":    "bearer",
        "board_label":  "Board ID",
        "board_help":   "Found in board URL: monday.com/boards/1234567890",
        "project_label":"Workspace Name",
        "project_help": "Name of your Monday workspace",
        "color":        "#FF3D57",
        "adapter":      "monday",
    },
    "Linear": {
        "icon":         "🟣",
        "vendor":       "Linear",
        "url_label":    "Linear API URL",
        "url_help":     "Always: https://api.linear.app — do not change",
        "url_example":  "https://api.linear.app",
        "auth_type":    "bearer",
        "email_label":  "Linear Email (optional)",
        "email_help":   "Your Linear login email — for reference only",
        "token_label":  "Linear API Key",
        "token_help":   "Linear → Settings → API → Personal API Keys → Create key",
        "token_link":   "https://linear.app/settings/api",
        "token_ph":     "lin_api_...",
        "test_path":    "/graphql",
        "test_auth":    "bearer",
        "board_label":  "Team ID",
        "board_help":   "Linear → Settings → Teams → copy the team identifier",
        "project_label":"Team Name",
        "project_help": "Name of your Linear team",
        "color":        "#5E6AD2",
        "adapter":      "linear",
    },
    "Custom / Other": {
        "icon":         "⚙️",
        "vendor":       "Custom",
        "url_label":    "Tool Base URL",
        "url_help":     "Base URL of your project management tool REST API",
        "url_example":  "https://your-tool.com/api",
        "auth_type":    "api_token",
        "email_label":  "Username / Email",
        "email_help":   "Your login username or email for this tool",
        "token_label":  "API Token / Password",
        "token_help":   "API token or password for authentication",
        "token_link":   "",
        "token_ph":     "Your token...",
        "test_path":    "/",
        "test_auth":    "basic",
        "board_label":  "Board / Project ID",
        "board_help":   "The ID of your board or project",
        "project_label":"Project Key / Name",
        "project_help": "Your project identifier",
        "color":        "#6366F1",
        "adapter":      "custom",
    },
}

TOOL_NAMES = list(TOOLS.keys())
